pipeline {
    agent {
        docker {
            image 'oavkdtv/centos-node:1.0.0' 
            args '-p 3300:3000' 
        }
    }
    environment {
        CI = 'true' 
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm config set http-proxy http://10.252.64.33:8080'
                sh 'npm config set https-proxy http://10.252.64.33:8080'
                sh 'npm install' 
            }
        }
        stage('Test') { 
            steps {
                sh 'npm run test' 
            }
        }
    }
}
node {
    stage 'Checkout'
        git url: 'https://github.com/oavkdtv/davedb-app'
    stage 'Build Docker'
        docker.build('davedb-app --build-arg HTTPS_PROXY=http://10.252.64.33:8080 --build-arg HTTP_PROXY=http://10.252.64.33:8080')
    stage 'deploy'
        sh 'docker stack deploy -c docker-compose.yml davedb-app'
}
